// Package notify renders owner notification emails for account review reports
// and delivers them through Gmail. Rendering is separate from send: the CLI
// plans messages first, then optionally sends with --send --yes or --redirect-prefix.
package notify

import (
	"fmt"
	"strings"
	"time"

	"github.com/openshift-online/finops-tools/cli/internal/format"
	"github.com/openshift-online/finops-tools/core/accountreview"
)

const responseDeadlineWeeks = 2

const actionRequiredSubjectPrefix = "⚠️ Action required: "

const actionRequiredIntro = `We are reviewing AWS accounts that may no longer be needed. Based on the information below, please reply to this email and tell us whether you want to:`

const actionRequiredOptions = `- Keep the account
- Delete the account
- Request modifications (describe what you need)`

func actionRequiredDeadlineText(accountCount int) string {
	phrase := "this AWS account"
	if accountCount > 1 {
		phrase = "these AWS accounts"
	}
	return fmt.Sprintf(
		"If we do not hear from you within %d weeks, we will proceed with deleting %s.",
		responseDeadlineWeeks,
		phrase,
	)
}

type Message struct {
	// To is the envelope recipient after redirect/owner resolution (same as DeliveryTo).
	To string `json:"to"`
	// IntendedTo is the resolved owner mailbox, even when DeliveryTo is a redirect address.
	IntendedTo string `json:"intended_to,omitempty"`
	// DeliveryTo is where Gmail actually sends (owner or PREFIX+owner@redhat.com).
	DeliveryTo string `json:"delivery_to,omitempty"`
	Subject    string `json:"subject"`
	TextBody   string `json:"text_body"`
	HTMLBody   string `json:"html_body"`
}

// RenderAccountEmail renders a single-account notification.
func RenderAccountEmail(report accountreview.AccountReport) Message {
	subject := actionRequiredSubjectPrefix + fmt.Sprintf("AWS account review: %s (%s)", report.AccountName, report.AccountID)
	return Message{
		To:         report.OwnerEmail,
		IntendedTo: report.OwnerEmail,
		Subject:    subject,
		TextBody:   renderTextBody([]accountreview.AccountReport{report}),
		HTMLBody:   renderHTMLBody([]accountreview.AccountReport{report}),
	}
}

// RenderOwnerGroupEmail renders a multi-account notification for one owner.
func RenderOwnerGroupEmail(group accountreview.OwnerGroup) Message {
	subject := actionRequiredSubjectPrefix + fmt.Sprintf("AWS account review: %d account(s)", len(group.Reports))
	return Message{
		To:         group.OwnerEmail,
		IntendedTo: group.OwnerEmail,
		Subject:    subject,
		TextBody:   renderTextBody(group.Reports),
		HTMLBody:   renderHTMLBody(group.Reports),
	}
}

func renderTextBody(reports []accountreview.AccountReport) string {
	var b strings.Builder
	writeActionRequiredText(&b, len(reports))
	for i, r := range reports {
		if i > 0 {
			b.WriteString("\n\n")
			b.WriteString(strings.Repeat("=", 48))
			b.WriteString("\n\n")
		} else {
			b.WriteString("\n\n")
		}
		writeAccountText(&b, r)
	}
	b.WriteString("\n\nGenerated by finops-tools\n")
	return b.String()
}

func writeAccountText(b *strings.Builder, r accountreview.AccountReport) {
	fmt.Fprintf(b, "Account: %s (%s)\n", r.AccountName, r.AccountID)
	if r.DisplayAlias != "" {
		fmt.Fprintf(b, "Alias: %s\n", r.DisplayAlias)
	}
	if r.OUPath != "" {
		fmt.Fprintf(b, "OU: %s\n", r.OUPath)
	}
	if len(r.Tags) > 0 {
		b.WriteString("Tags:\n")
		for _, t := range r.Tags {
			fmt.Fprintf(b, "  %s: %s\n", t.Key, t.Value)
		}
	}

	b.WriteString("\nMonthly costs (net amortized):\n")
	if r.MonthlyCosts.Error != "" {
		fmt.Fprintf(b, "  (unavailable: %s)\n", r.MonthlyCosts.Error)
	} else if len(r.MonthlyCosts.Months) == 0 {
		b.WriteString("  (no data)\n")
	} else {
		for _, m := range r.MonthlyCosts.Months {
			fmt.Fprintf(b, "  %s: %s\n", m.Month, format.FormatMoney(m.Amount, r.MonthlyCosts.Currency))
		}
		fmt.Fprintf(b, "  Total: %s\n", format.FormatMoney(r.MonthlyCosts.Total, r.MonthlyCosts.Currency))
	}

	if r.MonthlyCosts.Error == "" && len(r.MonthlyCosts.TopServices) > 0 {
		b.WriteString("\nTop services (last complete month):\n")
		for _, svc := range r.MonthlyCosts.TopServices {
			fmt.Fprintf(b, "  %s: %s\n", svc.Service, format.FormatMoney(svc.Amount, r.MonthlyCosts.Currency))
		}
	} else if r.MonthlyCosts.Error == "" && r.MonthlyCosts.TopServicesError != "" {
		fmt.Fprintf(b, "\nTop services (last complete month):\n  (unavailable: %s)\n", r.MonthlyCosts.TopServicesError)
	}

	writeInventoryText(b, r)
	if r.InventoryError != "" {
		fmt.Fprintf(b, "\nInventory warnings: %s\n", r.InventoryError)
	}
}

func writeInventoryText(b *strings.Builder, r accountreview.AccountReport) {
	inv := r.Inventory
	b.WriteString("\nResources:\n")
	fmt.Fprintf(b, "  EC2 instances: %d\n", len(inv.EC2Instances))
	for _, inst := range inv.EC2Instances {
		name := inst.Name
		if name == "" {
			name = "-"
		}
		fmt.Fprintf(b, "    %s  %s  %s  %s  %s\n", inst.InstanceID, name, inst.Type, inst.State, inst.Region)
	}

	fmt.Fprintf(b, "  RDS instances: %d\n", len(inv.RDSInstances))
	for _, db := range inv.RDSInstances {
		fmt.Fprintf(b, "    %s  %s  %s  %s  %s\n", db.InstanceID, db.Engine, db.Class, db.Status, db.Region)
	}

	fmt.Fprintf(b, "  RDS clusters: %d\n", len(inv.RDSClusters))
	for _, c := range inv.RDSClusters {
		fmt.Fprintf(b, "    %s  %s  %s  %s\n", c.ClusterID, c.Engine, c.Status, c.Region)
	}

	fmt.Fprintf(b, "  Route53 hosted zones: %d\n", len(inv.HostedZones))
	for _, z := range inv.HostedZones {
		kind := "public"
		if z.PrivateZone {
			kind = "private"
		}
		fmt.Fprintf(b, "    %s  %s  %d records\n", z.Name, kind, z.RecordCount)
	}

	fmt.Fprintf(b, "  Unattached EBS volumes: %d\n", len(inv.UnattachedEBS))
	fmt.Fprintf(b, "  Unassociated Elastic IPs: %d\n", len(inv.ElasticIPs))
	fmt.Fprintf(b, "  Load balancers: %d\n", len(inv.LoadBalancers))
	fmt.Fprintf(b, "  NAT gateways: %d\n", len(inv.NATGateways))
	fmt.Fprintf(b, "  S3 buckets: %d\n", len(inv.S3Buckets))
	fmt.Fprintf(b, "  Lambda functions: %d\n", len(inv.LambdaFunctions))
	fmt.Fprintf(b, "  VPCs: %d\n", len(inv.VPCs))
}

func writeActionRequiredText(b *strings.Builder, accountCount int) {
	b.WriteString("Action required\n\n")
	b.WriteString(actionRequiredIntro)
	b.WriteString("\n\n")
	b.WriteString(actionRequiredOptions)
	b.WriteString("\n\n")
	b.WriteString(actionRequiredDeadlineText(accountCount))
	b.WriteString("\n")
	b.WriteString(strings.Repeat("=", 48))
	b.WriteString("\n")
}

func renderHTMLBody(reports []accountreview.AccountReport) string {
	var b strings.Builder
	b.WriteString(`<!DOCTYPE html><html><head><meta charset="utf-8"><style>
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;line-height:1.5;color:#1f2328;background:#f6f8fa;margin:0;padding:1.5rem}
.container{max-width:900px;margin:0 auto}
section{background:#fff;border:1px solid #d0d7de;border-radius:8px;padding:1rem 1.25rem;margin-bottom:1rem}
h1{margin:0 0 .5rem;font-size:1.5rem}h2{margin:0 0 .75rem;font-size:1.1rem;color:#0969da}
table{width:100%;border-collapse:collapse;font-size:.9rem}th,td{text-align:left;padding:.4rem .6rem;border-bottom:1px solid #d0d7de}
th{color:#656d76}.amount{text-align:right;white-space:nowrap}.meta{color:#656d76;font-size:.9rem}
.action{background:#fff8c5;border:1px solid #d4a72c;border-radius:8px;padding:1rem 1.25rem;margin-bottom:1rem}
.action h2{margin:0 0 .75rem;font-size:1.1rem;color:#9a6700}
.action ul{margin:.5rem 0 0 1.25rem;padding:0}
footer{margin-top:1rem;color:#656d76;font-size:.85rem;text-align:center}
</style></head><body><div class="container">`)
	b.WriteString(fmt.Sprintf(`<header><h1>AWS account review</h1><p class="meta">Generated %s</p></header>`, generatedAt(reports).Format("2006-01-02 15:04 UTC")))
	writeActionRequiredHTML(&b, len(reports))

	for _, r := range reports {
		writeAccountHTML(&b, r)
	}
	b.WriteString(`<footer>Generated by finops-tools</footer></div></body></html>`)
	return b.String()
}

func writeAccountHTML(b *strings.Builder, r accountreview.AccountReport) {
	fmt.Fprintf(b, `<section><h2>%s (%s)</h2>`, htmlEscape(r.AccountName), htmlEscape(r.AccountID))
	if r.DisplayAlias != "" {
		fmt.Fprintf(b, `<p class="meta">Alias: %s</p>`, htmlEscape(r.DisplayAlias))
	}
	if r.OUPath != "" {
		fmt.Fprintf(b, `<p class="meta">OU: %s</p>`, htmlEscape(r.OUPath))
	}

	if len(r.Tags) > 0 {
		b.WriteString(`<table><thead><tr><th>Tag</th><th>Value</th></tr></thead><tbody>`)
		for _, t := range r.Tags {
			fmt.Fprintf(b, `<tr><td>%s</td><td>%s</td></tr>`, htmlEscape(t.Key), htmlEscape(t.Value))
		}
		b.WriteString(`</tbody></table>`)
	}

	b.WriteString(`<h2>Monthly costs</h2>`)
	if r.MonthlyCosts.Error != "" {
		fmt.Fprintf(b, `<p class="meta">Unavailable: %s</p>`, htmlEscape(r.MonthlyCosts.Error))
	} else {
		b.WriteString(`<table><thead><tr><th>Month</th><th class="amount">Amount</th></tr></thead><tbody>`)
		for _, m := range r.MonthlyCosts.Months {
			fmt.Fprintf(b, `<tr><td>%s</td><td class="amount">%s</td></tr>`, htmlEscape(m.Month), htmlEscape(format.FormatMoney(m.Amount, r.MonthlyCosts.Currency)))
		}
		if len(r.MonthlyCosts.Months) > 0 {
			fmt.Fprintf(b, `<tr><th>Total</th><td class="amount">%s</td></tr>`, htmlEscape(format.FormatMoney(r.MonthlyCosts.Total, r.MonthlyCosts.Currency)))
		}
		b.WriteString(`</tbody></table>`)
	}

	if r.MonthlyCosts.Error == "" && len(r.MonthlyCosts.TopServices) > 0 {
		b.WriteString(`<h2>Top services (last complete month)</h2><table><thead><tr><th>Service</th><th class="amount">Amount</th></tr></thead><tbody>`)
		for _, svc := range r.MonthlyCosts.TopServices {
			fmt.Fprintf(b, `<tr><td>%s</td><td class="amount">%s</td></tr>`, htmlEscape(svc.Service), htmlEscape(format.FormatMoney(svc.Amount, r.MonthlyCosts.Currency)))
		}
		b.WriteString(`</tbody></table>`)
	} else if r.MonthlyCosts.Error == "" && r.MonthlyCosts.TopServicesError != "" {
		fmt.Fprintf(b, `<h2>Top services (last complete month)</h2><p class="meta">Unavailable: %s</p>`, htmlEscape(r.MonthlyCosts.TopServicesError))
	}

	writeInventoryHTML(b, r)
	if r.InventoryError != "" {
		fmt.Fprintf(b, `<p class="meta">Inventory warnings: %s</p>`, htmlEscape(r.InventoryError))
	}
	b.WriteString(`</section>`)
}

func writeInventoryHTML(b *strings.Builder, r accountreview.AccountReport) {
	inv := r.Inventory
	b.WriteString(`<h2>Resources</h2>`)

	writeResourceTable(b, "EC2 instances", []string{"ID", "Name", "Type", "State", "Region"}, len(inv.EC2Instances), func(i int) []string {
		inst := inv.EC2Instances[i]
		name := inst.Name
		if name == "" {
			name = "-"
		}
		return []string{inst.InstanceID, name, inst.Type, inst.State, inst.Region}
	})

	writeResourceTable(b, "RDS instances", []string{"ID", "Engine", "Class", "Status", "Region"}, len(inv.RDSInstances), func(i int) []string {
		db := inv.RDSInstances[i]
		return []string{db.InstanceID, db.Engine, db.Class, db.Status, db.Region}
	})

	writeResourceTable(b, "RDS clusters", []string{"ID", "Engine", "Status", "Region"}, len(inv.RDSClusters), func(i int) []string {
		c := inv.RDSClusters[i]
		return []string{c.ClusterID, c.Engine, c.Status, c.Region}
	})

	writeResourceTable(b, "Route53 hosted zones", []string{"Name", "Type", "Records"}, len(inv.HostedZones), func(i int) []string {
		z := inv.HostedZones[i]
		kind := "public"
		if z.PrivateZone {
			kind = "private"
		}
		return []string{z.Name, kind, fmt.Sprintf("%d", z.RecordCount)}
	})

	fmt.Fprintf(b, `<p class="meta">Unattached EBS: %d · Unassociated EIPs: %d · Load balancers: %d · NAT gateways: %d · S3 buckets: %d · Lambda: %d · VPCs: %d</p>`,
		len(inv.UnattachedEBS), len(inv.ElasticIPs), len(inv.LoadBalancers), len(inv.NATGateways), len(inv.S3Buckets), len(inv.LambdaFunctions), len(inv.VPCs))
}

func generatedAt(reports []accountreview.AccountReport) time.Time {
	if len(reports) > 0 && !reports[0].GeneratedAt.IsZero() {
		return reports[0].GeneratedAt.UTC()
	}
	return time.Now().UTC()
}

func writeResourceTable(b *strings.Builder, title string, headers []string, count int, row func(int) []string) {
	fmt.Fprintf(b, `<h2>%s (%d)</h2>`, htmlEscape(title), count)
	if count == 0 {
		return
	}
	b.WriteString(`<table><thead><tr>`)
	for _, h := range headers {
		fmt.Fprintf(b, `<th>%s</th>`, htmlEscape(h))
	}
	b.WriteString(`</tr></thead><tbody>`)
	for i := 0; i < count; i++ {
		b.WriteString(`<tr>`)
		for _, cell := range row(i) {
			fmt.Fprintf(b, `<td>%s</td>`, htmlEscape(cell))
		}
		b.WriteString(`</tr>`)
	}
	b.WriteString(`</tbody></table>`)
}

func writeActionRequiredHTML(b *strings.Builder, accountCount int) {
	b.WriteString(`<section class="action"><h2>Action required</h2><p>`)
	b.WriteString(htmlEscape(actionRequiredIntro))
	b.WriteString(`</p><ul><li>Keep the account</li><li>Delete the account</li><li>Request modifications (describe what you need)</li></ul><p><strong>`)
	b.WriteString(htmlEscape(actionRequiredDeadlineText(accountCount)))
	b.WriteString(`</strong></p></section>`)
}

func htmlEscape(s string) string {
	replacer := strings.NewReplacer(
		"&", "&amp;",
		"<", "&lt;",
		">", "&gt;",
		`"`, "&quot;",
	)
	return replacer.Replace(s)
}
